### ISSUE TITLE
Simplify compatibility matrix with only the suggested versions for each k8s versions, and remove the older versions

### ISSUE THREAD

**Issue by nutellinoit** [sighupio/fury-distribution#83]
Hi all, our compatibility matrix is a little bit complicated, we should simplify and remove older unsupported versions (like below 1.20/1.19)

wdy think?

PS: also, we should order them not alphabetically but with the release dates, for example 1.22.1 is more recent than 1.23.1, and have more recent packages)

**Comment by ralgozino** [comment]
I agree, I had some improvements in mind already:

- Change the order of the Kubernetes version columns from "newer to older" instead of "older to newer" (i.e. 1.25, 1.24, 1.23, ... instead of 1.23, 1.24, 1.25...). In this way, you get the most recent information first without horizontal scrolling.
- Remove old releases from the main matrix, maybe move them to another file for historical reference, can be also as a list instead of a matrix. One can always check the `git` history, but I think it is worth it anyway.
- Mark unsupported releases as such.
- Link the versions to its release notes :o)

**Comment by nutellinoit** [comment]
I like this! Let's try 🚀

**Comment by ralgozino** [comment]
I'll open a PR with a proposal
